downstream_dependencies:  
  - bcforms
  - bpforms
  - conv_opt
  - datanator
  # - datanator_frontend
  - gdoc_down
  - h1_hesc
  - intro_to_wc_modeling
  - karr_lab_build_utils  
  - mycoplasma_pneumoniae
  - nose2unitth
  - obj_tables
  - rand_wc_model_gen
  - unitth
  - wc_cli
  - wc_analysis
  - wc_env_manager
  - wc_kb
  - wc_kb_gen
  - wc_lang
  - wc_model_gen
  - wc_rules
  - wc_sim
  - wc_test
  - wc_utils
email_notifications:
  - jonrkarr@gmail.com
